### ISSUE TITLE
Generated code imports using \ instead of /

### ISSUE THREAD

**Issue by ivopr** [vegardit/prisma-generator-nestjs-dto#10]
Example of generated code:
```ts
import {Authentication} from '..\..\authentication\entities\authentication.entity'


export class Account {
  email: string ;
name: string ;
authentication?: Authentication  | null;
authenticationId: string  | null;
createdAt: Date ;
updatedAt: Date ;
}
```

On windows 11, node lts

**Comment by benkroeger** [comment]
this is probably due to building on windows and the generator using [`path.sep`](https://github.com/vegardit/prisma-generator-nestjs-dto/blob/main/src/generator/helpers.ts#L174) and [`path.relative()`](https://github.com/vegardit/prisma-generator-nestjs-dto/blob/main/src/generator/helpers.ts#L129) from NodeJS core

**Comment by benkroeger** [comment]
can you provide a PR to wrap import paths with [slash](https://github.com/sindresorhus/slash)

**Comment by webdagger** [comment]
> can you provide a PR to wrap import paths with [slash](https://github.com/sindresorhus/slash)

#11 Does this fix it on windows?
